[workspace]
members = ["android/rust", "core", "native"]
resolver = "2"

[workspace.package]
version = "0.1.0"

[workspace.dependencies]
eframe = { version = "0.33.3", features = ["wgpu", "android-game-activity"] }
