[package]
name = "core"
edition = "2021"
version.workspace = true
publish = false

[dependencies]
eframe.workspace = true
reqwest = { version = "0.12.26", features = ["json", "rustls-tls"], default-features = false }
tokio = { version = "1.48.0", features = ["rt-multi-thread"] }
dotenv = "0.15.0"
